skywinder/ActionSheetPicker-3.0

Pickers/AbstractActionSheetPicker.m

update masterview frame and pickerview frame where toolbar hidden; add tap dismiss action actionsheet's window. reflect didSucceedWithAction when tap action fired.
This merge will fix #80.

Add TapAction For ActionSheetPickerView And Update The ActionSheetPickerView frame when toolbar hiden

---

Pickers/AbstractActionSheetPicker.h
Pickers/AbstractActionSheetPicker.m

Just a few lines of code...
Wanted to be able to configure the ActionSheet a little more, such as, backgroundColor or adding a visualEffectView.
Also didn't want to be forced to have the 8 pixel border on the sides. Some may want that, so I created an int for those some.

Exposed ActionSheet and created intVar for better config.

---

Pickers/AbstractActionSheetPicker.m

Fix tapDismissAction bug in iOS7

---

Pickers/ActionSheetMultipleStringPicker.h
Pickers/ActionSheetMultipleStringPicker.m

Looks like my editor also truncated some empty spaces too.

Fixes typo - ActionMultopleStringCancelBlock

---

CoreActionSheetPicker/CoreActionSheetPicker.xcodeproj/project.pbxproj
CoreActionSheetPicker/CoreActionSheetPicker.xcodeproj/xcshareddata/xcschemes/CoreActionSheetPicker.xcscheme
CoreActionSheetPicker/CoreActionSheetPicker/Info.plist
CoreActionSheetPicker/CoreActionSheetPickerTests/Info.plist
Example Projects/Example-for-iOS-7-and-6/ActionSheetPicker-iOS-5-7.xcodeproj/xcshareddata/xcschemes/ActionSheetPicker-iOS-5-7.xcscheme
Example Projects/ObjC-Example/ActionSheetPicker Tests/ActionSheetPicker Tests-Info.plist
Example Projects/ObjC-Example/ActionSheetPicker-Info.plist
Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj
Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/xcshareddata/xcschemes/ActionSheetPicker.xcscheme
Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/xcshareddata/xcschemes/ActionSheetPickerTests.xcscheme
Example Projects/Swift-Example/Swift-Example.xcodeproj/project.pbxproj
Example Projects/Swift-Example/Swift-Example/Images.xcassets/AppIcon.appiconset/Contents.json
Example Projects/Swift-Example/Swift-Example/Images.xcassets/LaunchImage.launchimage/Contents.json
Example Projects/Swift-Example/Swift-Example/Info.plist
Example Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift
Example Projects/Swift-Example/Swift-ExampleTests/Info.plist

Swift 2.0 update

---

Pickers/ActionSheetPicker.h

Added missing header reference in ActionSheetPicker.h

Added missing header reference

---

Example Projects/ObjC-Example/Example/Classes/ActionSheetPickerTableViewController.m
Pickers/AbstractActionSheetPicker.h
Pickers/AbstractActionSheetPicker.m
Pickers/ActionSheetStringPicker.m

make font of picker label ready for customize.

---

Example Projects/Example-for-iOS-7-and-6/Example/Classes/ActionSheetPickerCustomPickerDelegate.m
Example Projects/ObjC-Example/ActionSheetPicker Tests/ActionSheetCustomPickerTestDelegate.m
Example Projects/ObjC-Example/Example/Classes/ActionSheetPickerCustomPickerDelegate.m
Pickers/AbstractActionSheetPicker.h
Pickers/ActionSheetCustomPicker.h
Pickers/ActionSheetCustomPicker.m
Pickers/ActionSheetDatePicker.h
Pickers/ActionSheetDatePicker.m
Pickers/ActionSheetDistancePicker.h
Pickers/ActionSheetDistancePicker.m
Pickers/DistancePickerView.m
Pickers/SWActionSheet.h

Use (instancetype) instead of (id). Its safer, compiler can catch errors and _plays nicely with swift_.

Use modern objective c initializer syntax

---

Pickers/AbstractActionSheetPicker.m

Fixes presentation issue on iPads

---

Example Projects/Swift-Example/Podfile
Example Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift

This commit resolves #261

---

BASIC-USAGE.md
README.md

@skywinder - updated Readme and basic-usage with blur effect ability.

Blur effect readme

---

Example Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift
Pickers/AbstractActionSheetPicker.h
Pickers/AbstractActionSheetPicker.m

Add method to set text color: `setTextColor`

Add method to set text color: `setTextColor`

---

Example Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift
Pickers/AbstractActionSheetPicker.h
Pickers/AbstractActionSheetPicker.m

Now you can use `toolbarButtonsColor` property to setup desired color.
this PR closes #54, #175, #230

add ability to set toolbar buttons color

---

README.md

Fix highlight ReadME

---

Pickers/ActionSheetLocalePicker.h
Pickers/ActionSheetMultipleStringPicker.h
Pickers/ActionSheetStringPicker.h

Fixes documentation

---

Pickers/AbstractActionSheetPicker.h
Pickers/AbstractActionSheetPicker.m
Pickers/SWActionSheet.h
Pickers/SWActionSheet.m

By default it will use the current one (UIWindowLevelAlert), but if you need a custom one, you will just have to change the option 🙃

Add option to customise window level presentation

---

Example Projects/Swift-Example/Swift-Example.xcodeproj/project.pbxproj
Example Projects/Swift-Example/Swift-Example/AppDelegate.swift
Example Projects/Swift-Example/Swift-Example/Base.lproj/Main.storyboard
Example Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift
Example Projects/Swift-Example/Swift-ExampleTests/Swift_ExampleTests.swift
Pickers/ActionSheetMultipleStringPicker.m

- TitleTextAttributes were not picking up for the multiple string picker
- examples updated to swift 3

Change font in Multiple String picker

---

.travis.yml
Pickers/SWActionSheet.m

Handle UIWindow for iOS 13 changes

Add iOS 13 support

---

Pickers/AbstractActionSheetPicker.m
Pickers/SWActionSheet.m

support dynamic background color in iOS 13
Will close #424

Support iOS 13 Dark Mode

---

.all-contributorsrc
Example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
README.md

Add more attention to the line:
Also added links to contributors, that help me a lot for last time.

Add contributorsi & update readme

---

AUTHORS.md
BASIC-USAGE.md
CONTRIBUTING.md
README.md

Fix some markdown issue following the markdownlint specification (https://github.com/markdownlint/markdownlint)

Improve Markdown syntax several .md files

---

README.md

This PR involve only the README.md file. Complete list of changes:
- Add Discord invite link
- Fix table of contents order
- Fix issue with a bare link
- Remove broken link in Contributing section

Add Discord link and fix some minor issues in README.md file

---

ActionSheetPicker-3.0.podspec

as discussed https://github.com/skywinder/ActionSheetPicker-3.0/pull/455#issuecomment-568773844

Update source patterns

---

Example Projects/ObjC-Example/Example/Classes/ActionSheetPickerTableViewController.m
Pickers/AbstractActionSheetPicker.m
Pickers/SWActionSheet.h
Pickers/SWActionSheet.m

This will fix #460.
The PR #399 broke rotation. Now it fixed.

Fix rotation issues.

---

Package.swift

Fixed target for `SPM` - `Package.swift` file

Fixed target for SPM - Package.swift file

---

README.md

Issue 344 - Fixed typo in ReadMe for Objective C - NSInteger

---

README.md

Added Swift Package Instructions.

Add Swift Package Manager instruction

---

Package.swift

Fix SPM issue (#525)

---

CoreActionSheetPicker/CoreActionSheetPicker/Pickers/AbstractActionSheetPicker.m
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/DistancePickerView.m
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/SWActionSheet.m

Issue 538 - Remove conditional statements less than iOS9

---

CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetCustomPicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetCustomPickerDelegate.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetDatePicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetDistancePicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetLocalePicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetMultipleStringPicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetStringPicker.h
CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/CoreActionSheetPicker.h

[Fix] import issue on Swift Pacakge

---

ActionSheetPicker-3.0.podspec

Update changelog later via `$ github_changelog_generator -u github-changelog-generator -p ActionSheetPicker-3.0`

Release 2.7.2

---

.github/workflows/DeployCocoaPods.yml
ActionSheetPicker-3.0.podspec

As title, add env COCOAPODS_TRUNK_TOKEN

Fixed DeployCocoaPods Github Action

---

.github/workflows/CIBuild.yml
.github/workflows/UpdateChangelog.yml
CHANGELOG.md

* Create UpdateChangelog.yml
* Update and rename ci.yml to CIBuild.yml
* Update CIBuild.yml
---------

Infra GitHub actions (#1)
